
    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table cuidarapp.tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table cuidarapp.tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table cuidarapp.tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table cuidarapp.tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table cuidarapp.tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table cuidarapp.tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table cuidarapp.tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table cuidarapp.tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table cuidarapp.tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table cuidarapp.tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table cuidarapp.tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references cuidarapp.tb_atendente

    alter table cuidarapp.tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references cuidarapp.tb_local

    alter table cuidarapp.tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references cuidarapp.tb_medico

    alter table cuidarapp.tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references cuidarapp.tb_paciente

    alter table cuidarapp.tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references cuidarapp.tb_permissao

    alter table cuidarapp.tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references cuidarapp.tb_grupo

    alter table cuidarapp.tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references cuidarapp.tb_grupo

    alter table cuidarapp.tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references cuidarapp.tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario

    create table tb_atendente (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_exame (
       id bigint generated by default as identity,
        data_exame TIMESTAMP not null,
        nome_exame varchar(100) not null,
        observacao varchar(500),
        situacao tinyint(1) DEFAULT 1 not null not null,
        valor decimal(12,2) not null,
        atendente_id bigint,
        local_id bigint,
        medico_id bigint,
        paciente_id bigint not null,
        primary key (id)
    )

    create table tb_grupo (
       id bigint generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_grupo_permissao (
       grupo_id bigint not null,
        permissao_id bigint not null
    )

    create table tb_local (
       id bigint generated by default as identity,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        nome_local varchar(255) not null,
        primary key (id)
    )

    create table tb_medico (
       id bigint generated by default as identity,
        is_ativo boolean default true not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_paciente (
       id bigint generated by default as identity,
        rg varchar(9),
        is_aceite BIT,
        codigo varchar(255),
        cont_celular varchar(15),
        cont_facebook varchar(50),
        cont_instagram varchar(50),
        cont_email varchar(50),
        cont_telefone varchar(14),
        is_convenio BIT,
        data_atualizacao datetime not null,
        data_cadastro datetime,
        data_nasc TIMESTAMP,
        deficiencia varchar(50),
        deficiencia_familia varchar(255),
        is_deficiente BIT,
        end_bairro varchar(50),
        end_cep varchar(11),
        end_cidade varchar(50),
        end_numero varchar(20),
        end_observacao varchar(100),
        end_rua varchar(75),
        end_tipo_residencia varchar(11),
        estado_civil varchar(10),
        filhos integer,
        idade integer,
        indicacao varchar(100),
        is_ativo BIT,
        nome varchar(100),
        nome_responsavel_paciente varchar(100),
        observacao varchar(500),
        profissao varchar(30),
        primary key (id)
    )

    create table tb_permissao (
       id bigint generated by default as identity,
        descricao varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    )

    create table tb_usuario (
       usuario_id bigint generated by default as identity,
        login varchar(255),
        senha varchar(255),
        primary key (usuario_id)
    )

    create table tb_usuario_grupo (
       usuario_id bigint not null,
        grupo_id bigint not null
    )

    alter table tb_exame 
       add constraint FKif7kr1cj0j0mck7brn8vdb7ae 
       foreign key (atendente_id) 
       references tb_atendente

    alter table tb_exame 
       add constraint FKc7y99e7xuyfibmw70ujm5vw3e 
       foreign key (local_id) 
       references tb_local

    alter table tb_exame 
       add constraint FKrpxjnp4a64389ey01nu3xw8js 
       foreign key (medico_id) 
       references tb_medico

    alter table tb_exame 
       add constraint FKgau38nc1cts62fs30my1j6k13 
       foreign key (paciente_id) 
       references tb_paciente

    alter table tb_grupo_permissao 
       add constraint FKebkjqmqseopi0eipijfo06vh8 
       foreign key (permissao_id) 
       references tb_permissao

    alter table tb_grupo_permissao 
       add constraint FKc35tefcxk6t0b4u5qaenlv63e 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKfox4y8jslkfybem54i4jyndnj 
       foreign key (grupo_id) 
       references tb_grupo

    alter table tb_usuario_grupo 
       add constraint FKos1k9g527yqpdorasypy0h72d 
       foreign key (usuario_id) 
       references tb_usuario
