# comentado ate que volte a funcionar
# # criando uma imagem do nginx
# FROM nginx:1.19.6-alpine
#
# # comando para remover o arquivo de config padrao, pois foi criado um personalizado (nginx.config)
# RUN rm /etc/nginx/conf.d/default.conf
#
# # copiando o arquivo personalizado (nginx.config) no lugar do default
# COPY nginx.conf /etc/nginx/conf.d/default.conf